version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    privileged: true
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    volumes:
      - influxdb-volume:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana

volumes:
  influxdb-volume:
  grafana-volume:
